library(readr)
dat <-read.csv('LifeExpectancyData.csv')
dat
dat <-read_delim("LifeExpectancyData.tsv", col_names = TRUE, delim = "\t", na="")
dat
library(dbplyr)
install.packages('dbplyr')
con <-src_mysql("etcsite_charaparser", user="termsuer", password="termspassword", host="localhost")
library(DBI)
install.packages("RMySQL")
library(RMySQL)
drv <-dbDriver("MySQL")
con <-dbConnect(drv, dbname="etcsite_charaparser", username="root", password="Sandia005!", host="localhostMsSQL80")
data <-dbGetQuery(con, "select * from 1_allwords")
library(readr)
wide <-read_delim("wide.txt", delim = " ", skip = 1, col_names = c("Country", "Year", "Life expectancy", "GDP"))
data("LifeExpectancy", package="DMwR2")
LifeExpectancyData[48, "Life expectancy"] <-mean(LifeExpectancyData$percentage_expenditure, na.rm=TRUE)

qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
install.packages("dbplyr")
library(dbplyr)
library(tibble)
library(tidyr)
library(ggplot2)
library(car)
ggplot(LifeExpectancy$Country, main="Coutnries QQ")
qqplot(LifeExpectancy$Country, main="Countries QQ")
qqplot(LifeExpectancy$Country, LifeExpectancy$LifeExpectancy, main="Countries QQ")
LifeExpectancy[48, "Life expectancy"] <- mean(LifeExpectancy$'Life expectancy', na.rm = TRUE)
LifeExpectancy[48, "Life expectancy"] <- mean(LifeExpectancy$"percentage expendatures")
mode(LifeExpectancy$"percentage expendature")
mode(LifeExpectancy$percentage_expecdature)
LifeExpectancy$BMI
LifeExpectancy$Year
mode(LifeExpectancyData$Year)
LifeExpectancyData[48, "Life expectancy"] <-mean(LifeExpectancyData$`percentage expenditure`)
qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
end()
+ qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
+ qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
+ qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
LifeExpectancyData[48, "Life expectancy"] <-mean(LifeExpectancyData$`percentage expenditure`, na.rm=TRUE)
qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
View(LifeExpectancy)
install.packages('DMwR2')
library(DMwR2)
LifeExpectancyData
LifeExpectancyData[48,]
install.packages("car")
library(car)
qqPlot(LifeExpectancyData$Population, main = "Life Expectancy QQ Plot")
LifeExpectancyData[48, "population"] <-mean(LifeExpectancyData$Population, na.rm = TRUE)
symnum(cor(LifeExpectancyData[4:20], use = "complete.obs"))
