library(readr)
dat <-read.csv('LifeExpectancyData.csv')
dat
dat <-read_delim("LifeExpectancyData.tsv", col_names = TRUE, delim = "\t", na="")
dat
library(dbplyr)
install.packages('dbplyr')
con <-src_mysql("etcsite_charaparser", user="termsuer", password="termspassword", host="localhost")
library(DBI)
install.packages("RMySQL")
library(RMySQL)
drv <-dbDriver("MySQL")
con <-dbConnect(drv, dbname="etcsite_charaparser", username="root", password="Sandia005!", host="localhostMsSQL80")
data <-dbGetQuery(con, "select * from 1_allwords")
library(readr)
wide <-read_delim("wide.txt", delim = " ", skip = 1, col_names = c("Country", "Year", "Life expectancy", "GDP"))
data("LifeExpectancy", package="DMwR2")
LifeExpectancyData[48, "Life expectancy"] <-mean(LifeExpectancyData$percentage_expenditure, na.rm=TRUE)

qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
install.packages("dbplyr")
library(dbplyr)
library(tibble)
library(tidyr)
library(ggplot2)
ggplot(LifeExpectancy$Country, main="Coutnries QQ")
qqplot(LifeExpectancy$Country, main="Countries QQ")
qqplot(LifeExpectancy$Country,LifeExpectancy$LifeExpectancy, main="Countries QQ")
LifeExpectancy[48, "Life expectancy"] <- mean(LifeExpectancy$'Life expectancy', na.rm = TRUE)
LifeExpectancy[48, "Life expectancy"] <- mean(LifeExpectancy$"percentage expendatures")
mode(LifeExpectancy$"percentage expendature")
mode(LifeExpectancy$percentage_expecdature)
LifeExpectancy$BMI
LifeExpectancy$Year
mode(LifeExpectancyData$Year)
LifeExpectancyData[48, "Life expectancy"] <-mean(LifeExpectancyData$`percentage expenditure`)
LifeExpectancyData[48, "Life expectancy"] <-mean(LifeExpectancyData$`percentage expenditure', na.rm=TRUE)
qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
end()
+ qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
+ qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
+ qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
LifeExpectancyData[48, "Life expectancy"] <-mean(LifeExpectancyData$percentage_expenditure, na.rm=TRUE)
qqPlot(LifeExpectancyData$Year, main = "Expenditure per year")
View(LifeExpectancy)
install.packages(DMwR2)
install.packages('DMwR2')
library(DMwR2)
data(LifeExpectancyData, package='DMwR2')
LifeExpectancyData
LifeExpectancyData[48,]
install.packages("car")
library(car)
qqPlot(LifeExpectancyData$`Life expectancy`, main = "Life Expectancy QQ Plot")
qqPlot(LifeExpectancyData$Population, main = "Life Expectancy QQ Plot")
qqPlot(LifeExpectancyData$`Life expectancy`, main = "Life Expectancy QQ Plot")
LifeExpectancyData[48, "population"] <-mean(LifeExpectancyData$Population, na.rm = TRUE)
qqPlot(LifeExpectancyData$`Life expectancy`, main = "Life Expectancy")
median(LifeExpectancyData$`percentage expenditure`, na.rm = TRUE)
mean(LifeExpectancyData$`percentage expenditure`, na.rm = TRUE)
LifeExpectancyData[is.na(LifeExpectancyData$`percentage expenditure`), "PE"] <- median(LifeExpectancyData, na.rm = TRUE)
LifeExpectancyData[is.na(LifeExpectancyData$`percentage expenditure`), "PE"] <- median(LifeExpectancyData$`percentage expenditure`, na.rm = TRUE)
symnum(cor(LifeExpectancyData[, 3:22], use = "complete.obs"))
symnum(cor(LifeExpectancyData[3:22], use = "complete.obs"))
symnum(cor(LifeExpectancyData[3, 4:22], use = "complete.obs"))
symnum(cor(LifeExpectancyData[3, 4:20], use = "complete.obs"))
symnum(cor(LifeExpectancyData[ , 4:20], use = "complete.obs"))
LifeExpectancyData <- LifeExpectancyData[-manyNAs(LifeExpectancyData), ]
m = lm(LifeExpectancyData$Alcohol ~ LifeExpectancyData$`percentage expenditure`, data = LifeExpectancyData)
call:
m = lm(LifeExpectancyData$Alcohol ~ LifeExpectancyData$`percentage expenditure`, data = LifeExpectancyData)
m = lm(LifeExpectancyData$Alcohol ~ LifeExpectancyData$`percentage expenditure`, data = LifeExpectancyData)
summary(m)
F-statistic:   391 on 1 and 2536 DF,  p-value: < 2.2e-16
LifeExpectancyData$`percentage expenditure`
m = lm(LifeExpectancyData$`Life expectancy` ~ LifeExpectancyData$`percentage expenditure`, data = LifeExpectancyData)
summary(m)
