---
title: "hmwk5_classification_performance-estimation"
author: "Laura.w"
date: "11/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1)Install Packages and load libraries; then load the data
```{r}
suppressPackageStartupMessages(install.packages("performanceEstimation"))
suppressPackageStartupMessages(install.packages("e1071"))
library(performanceEstimation)
library(e1071)
library(nnet)

data("iris")
data("swiss")
data("mtcars")

```

2) Performance Estimation - the result of this signal run is not 1, but .966
```{r}
res1 <- performanceEstimation(PredTask(Species ~ .,iris),
                              Workflow(learner="svm"),
                              EstimationTask(metrics = "acc",
                              method=Holdout(hldSz = .2)))
```

```{r}
summary(res1)
```

```{r}
res1 <- performanceEstimation(PredTask(Species ~ .,iris),
                              Workflow(learner="svm"),
                              EstimationTask(metrics = "acc",
                              method=Holdout(nReps=10, hldSz = .2)))
```

```{r}
summary(res1)
```

```{r}
res <- performanceEstimation(
  c(PredTask(Infant.Mortality ~.,swiss), PredTask(mpg ~., mtcars)),
  c(workflowVariants(learner="svm",
                     learner.pars=list(cost=c(1,10), gamma=c(0.01,0.5))),
    workflowVariants(learner="nnet",
                     learner.pars=list(size=c(3, 6), decay=c(.01, .001)))),
  EstimationTask(metrics = "mse", method =CV(nReps=1, nFolds=10))
)
```

```{r}
summary(res)
```

```{r}
topPerformers(res)
```

```{r}
getWorkflow("svm.v2", res)
```

```{r}
(pres <- pairedComparisons(res, "nnet.v2"))

```

```{r}
myWF <- function(form,train, test, wL=.5, ...) {
  require(rpart,quietly = TRUE)
  ml <- lm(form,train)
  mr <- rpart(form,train)
  pl <- predict(ml, test)
  pr <- predict(mr, test)
  ps <- wL*pl+(1-wL)*pr
  list(trues=responseValues(form, test),preds=ps)
}

resmywf <- performanceEstimation(
  PredTask(mpg ~.,mtcars),
  workflowVariants(wf="myWF", wL=seq(0,1,by=.1)),
  EstimationTask(metrics = "mae", method = Bootstrap(nReps = 50))
)
summary(resmywf)
```