---
title: 'Homework #3'
author: "Kelsey Gonzalez"
date: "October 2, 2019"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
<!-- font: georgia -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4.2 (a & b) 
>4.2 Briefly compare the following concepts. You may use an example to explain your
point(s).
(a) Snowflake schema, fact constellation, starnet query model


>(b) Data cleaning, data transformation, refresh




## 4.3 (a, b, & c)
>4.2 Briefly compare the following concepts. You may use an example to explain your
point(s).
(a) Snowflake schema, fact constellation, starnet query model

>(b) Data cleaning, data transformation, refresh

>(c) Starting with the base cuboid [day,doctor,patient], what specific OLAP operations
should be performed in order to list the total fee collected by each doctor in 2010?
you

## 4.4
>4.4 Suppose that a data warehouse for Big University consists of the four dimensions student, course, semester, and instructor, and two measures count and avg grade. At the
lowest conceptual level (e.g., for a given student, course, semester, and instructor combination), the avg grade measure stores the actual course grade of the student. At higher
conceptual levels, avg grade stores the average grade for the given combination.
(a) Draw a snowflake schema diagram for the data warehouse.


>(b) Starting with the base cuboid [student,course,semester,instructor], what specific
OLAP operations (e.g., roll-up from semester to year) should you perform in order
to list the average grade of CS courses for each Big University student.



>(c) If each dimension has five levels (including all), such as “student < major < status <
university < all”, how many cuboids will this cube contain (including the base and
apex cuboids)?



## 4.5
>4.4 Suppose that a data warehouse for Big University consists of the four dimensions student, course, semester, and instructor, and two measures count and avg grade. At the
lowest conceptual level (e.g., for a given student, course, semester, and instructor combination), the avg grade measure stores the actual course grade of the student. At higher
conceptual levels, avg grade stores the average grade for the given combination.
(a) Draw a snowflake schema diagram for the data warehouse.



>(b) Starting with the base cuboid [student,course,semester,instructor], what specific
OLAP operations (e.g., roll-up from semester to year) should you perform in order
to list the average grade of CS courses for each Big University student.


>(c) If each dimension has five levels (including all), such as “student < major < status <
university < all”, how many cuboids will this cube contain (including the base and
apex cuboids)?

